### ISSUE TITLE
Add LUCID

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcds-envs#102]
https://github.com/pcdshub/lucid

**Comment by ZLLentz** [comment]
I'm happy to add this once it's on conda or pip

**Comment by klauer** [comment]
https://github.com/conda-forge/lucid-feedstock

**Comment by ZLLentz** [comment]
This is now blocked on the incompatibility between `pmgr` and `lucid`.

`pmgr` requires a modified build of `pyqt` and `lucid` requires a newer one. `pmgr` is needed in the environment for the `hutch-python` deployments as it will be used in the lcls hxr hutches. I see a few possible solutions:

1. Make another modified build of `pyqt`
2. Split the `pmgr` package into a `pmgr-core` that only includes the database calls with no `pyqt` dependencies and a `pmgr` package that does have the `pyqt` dependency. Only include the core version in the environment because the GUI is launched by other means anyway.
3. Make an environment split for `hutch-python` vs `lucid`

I prefer 2 as the solution because it solves the pyqt problem for a long time

**Comment by hhslepicka** [comment]
I vote for option 2 as well.
@ZLLentz do you have the patch easy at hand? We could try to propose it at the conda-forge channel for PyQt and maybe solve this problem there. (I can't promise that folks will accept it but it is worth a try)

**Comment by ZLLentz** [comment]
The patch is somewhere in the `pcds-recipes` repo if you think it's worth a try

I think 2 is a good thing to do regardless of upstream pyqt getting our random patch

**Comment by klauer** [comment]
(2) seems good - unifying would be great.
